@startuml ERD

title ERD Upk Mande Finance Systems

!pragma layout graphviz
skinparam linetype ortho


' ==============
' Enum          
' ==============

enum RoleEnum{
  -ANGGOTA
  -ADMIN
  -AKUNTAN
  -PENGELOLA_PENDANAAN
  -KEPALA_INSTITUSI
}

enum EnumStatusPengajuanAnggota{
  -PROSES_PENGAJUAN
  -DITERIMA
  -DITOLAK
}

enum EnumStatusKelompok{
  -AKTIF
  -NONAKTIF
}

enum EnumStatusPengajuanPinjaman{
  -DITOLAK
  -PROSES_PENGAJUAN
  -DISETUJUI
  -DIBATALKAN
}

enum EnumStatusPengajuanPinjaman{
  -DITOLAK
  -PROSES_PENGAJUAN
  -DISETUJUI
  -DIBATALKAN
}

enum EnumTipeTransaksi{
  -MASUK
  -KELUAR
  -TRANSFER
}

enum EnumTenor{
  -BULAN_3
  -BULAN_6
  -BULAN_9
  -BULAN_12
}

enum EnumStatusJadwalPencairan{
  -BELUM_TERJADWAL
  -TERJADWAL
  -TELAH_DICAIRKAN
  -DIBATALKAN
}

enum EnumStatusPinjamanKelompok{
  -MENUNGGAK
  -BERLANGSUNG
  -SELESAI
}

enum EnumStatusCicilanKelompok{
  -SUDAH_BAYAR
  -BELUM_BAYAR
  -TELAT_BAYAR
  -DIBATALKAN
}


' ==============
' Tables        
' ==============
entity "users" {
  + id : BigInt
  --
  -name : string
  -email : string
  -password : string
  -role : EnumRole
}

entity pengajuan_keanggotaan{
  * id : BigInt
  - users_id : BigInt
  --
  -nik : string
  -ktp : text
  -nama_lengkap : string
  -alamat : string
  -nomor_rekening : string
  -nomor_telepon : text
  -status : EnumStatusPengajuanKeanggotaan
  -catatan : text
}

entity "rekening" {
  + id : BigInt
  --
  -name : string
  -saldo : decimal(15, 2)
}

entity "transaksi_rekening" {
  + id : BigInt
  + rekening_id : BigInt
  --
  -rekening_id : foreignId
  -nominal : decimal(15, 2)
  -keterangan : text
  -tipe_transaksi : EnumTipeTransaksi
}

entity "kelompok" {
  + id : BigInt
  + users_id : BigInt
  --
  -name : string
  -limit_per_anggota : decimal(15, 2)
  -status : EnumStatusKelompok
}

entity "anggota_kelompok" {
  + id : BigInt
  + kelompok_id : BigInt
  --
  -nik : string
  -name : string
  -alamat : longText
  -nomor_telepon : text
}

entity "pengajuan_pinjaman" {
  + id : BigInt
  + kelompok_id : BigInt
  --
  -file_proposal : string
  -nominal_pinjaman : decimal(15, 2)
  -tenor : integer
  -catatan : longText
  -tanggal_pengajuan : dateTime
  -tanggal_disetujui : dateTime
  -tanggal_ditolak : dateTime
  -status : EnumStatusPengajuanPinjaman
}

entity "jadwal_pencairan" {
  + id : BigInt
  + pengajuan_pinjaman_id : BigInt
  --
  -status : EnumStatusJadwalPencairan
  -tanggal_pencairan : dateTime
}

entity "pinjaman_kelompok" {
  + id : BigInt
  + kelompok_id : BigInt
  + jadwal_pencairan_id : foreignId
  + pengajuan_pinjaman_id : foreignId
  --
  -tenor : integer
  -bunga : decimal(5, 2)
  -status : EnumStatusPinjamanKelompok
  -nominal_pinjaman : decimal(15, 2)
  -tanggal_mulai : dateTime
}

entity "cicilan_kelompok" {
  + id : BigInt
  + pinjaman_kelompok_id : BigInt
  --
  -status : EnumStatusCicilanKelompok
  -nominal_cicilan : decimal(15, 2)
  -bukti_pembayaran : string
  -tanggal_dibayar : dateTime
  -tanggal_jatuh_tempo : string
}

entity "settings" {
  + id : BigInt
  --
  -key : string
  -value : string
  -type : string
  -group : string
}

users ||---|| kelompok
users ||--o{ pengajuan_keanggotaan

rekening ||--o{ transaksi_rekening

kelompok ||--o{ anggota_kelompok
kelompok ||--o{ pengajuan_pinjaman
kelompok ||--o{ pinjaman_kelompok

pengajuan_pinjaman ||--o{ jadwal_pencairan
pengajuan_pinjaman ||--o{ pinjaman_kelompok

jadwal_pencairan ||--o{ pinjaman_kelompok
pinjaman_kelompok ||--o{ cicilan_kelompok

@enduml
